package ule.jescuj00.fridgey.di

import org.koin.android.ext.koin.androidContext
import org.koin.core.module.Module
import org.koin.core.qualifier.named
import org.koin.dsl.module
import ule.jescuj00.fridgey.data.auth.AppleSignInHelper
import ule.jescuj00.fridgey.data.auth.GoogleSignInHelper
import ule.jescuj00.fridgey.data.db.DatabaseDriverFactory

/**
 * Supplies Android-only bindings: the [DatabaseDriverFactory] (built with the
 * application [android.content.Context] registered via `androidContext(...)`)
 * and the platform sign-in helpers.
 *
 * The Web OAuth Client ID needed by [GoogleSignInHelper] is provided as a
 * named string by the composeApp module — this lets us read
 * `R.string.default_web_client_id` (auto-generated by the google-services
 * plugin) without making the shared module depend on the application's R.
 */
const val GOOGLE_WEB_CLIENT_ID_QUALIFIER = "googleWebClientId"

fun androidModule(): Module = module {
    single { DatabaseDriverFactory(androidContext()) }

    // No Context here: GoogleSignInHelper takes the Activity per call (via
    // the launcher param) so it doesn't hold a long-lived Activity reference.
    single {
        GoogleSignInHelper(
            serverClientId = get(named(GOOGLE_WEB_CLIENT_ID_QUALIFIER))
        )
    }
    single { AppleSignInHelper() }
}
